# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo:3.6.2
    ports:
      - 27017:27017
  app:
    container_name: app
    restart: always
    build:
      context: .
      args:
        RELEASE_VERSION: "2.0.0-SNAPSHOT"
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo